trigger:
- master

pool:
  name: 'sandeep'   # your self-hosted agent pool

variables:
  solution: 'src/WebApp/WebApp.sln'    # 👈 update this if your .sln is elsewhere
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
# Checkout source code
- checkout: self

# Install NuGet
- task: NuGetToolInstaller@1

# Restore NuGet packages
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

# Build the solution
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# Run unit tests
- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# Publish the artifact (WebApp.zip)
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(build.artifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

# Deploy to Azure Web App
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1(f823c456-be00-4f70-b511-e414d8f34e46)'  # service connection name
    appType: 'webApp'
    appName: 'cicdapp'   # must be globally unique in Azure
    package: '$(Build.ArtifactStagingDirectory)/WebApp.zip'
    deploymentMethod: 'auto'
